# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o bin/api ."
  bin = "bin/api"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "vendor"]

[watch]
  include = ["."]
  exclude = ["bin", "vendor"]

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  run = "magenta"