version: "3.9"

services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: my-mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/var/lib/mongodb_data:/data/db
#  adminer:
#    image: adminer:4.8.1
#    restart: always
#    ports:
#      - 8081:8081

#We simply host a PostgresSQL service on port 5432 (default) and map its original volume to ./data/db (for data persistance) in our current folder,
#with the admin interface on port 8080.

#docker compose -f docker-compose.yml up

